name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: build
        run: ./pbl-12-13/muji/gradlew clean build

      - name: make zip
        run: zip -qq -r ./goorm.zip /pbl-12-13/muji

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ./goorm.zip s3://awsgoorm-bucket/goorm.zip

      - name: Code deploy
        run: aws deploy create-deployment --application-name goormtricount
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name group1
          --s3-location bucket=awsgoorm-bucket,bundleType=zip,key=goorm.zip